### ISSUE TITLE
Sending email doesn't work

### ISSUE THREAD

**Issue by aafanasev** [PragmaticMates/realia#1]
Method **Realia_Query::get_property_agents** returns array of IDs, but used as object **$agent->ID**

https://github.com/PragmaticMates/realia/blob/master/includes/post-types/class-realia-post-type-property.php

```
$agent = Realia_Query::get_property_agents( $post->ID );
if ( ! empty( $agent ) ) {
    $email = get_post_meta( $agent->ID, REALIA_AGENT_PREFIX . 'email', true );
    ...   
}
```

**Comment by eriktelepovsky** [comment]
Yes, you are right. Thank you. It is fixed now.

**Comment by lukasvinclav** [comment]
Fixed
