### ISSUE TITLE
Google map don't work

### ISSUE THREAD

**Issue by themaniac** [PragmaticMates/realia#2]
When i try to create a new property on realia (backend and/or frontend page), i cannot see the google map widget because it ask for "google api key". 

I've added the api key on the cmb2 google map field, now on the js console i have no errors... BUT... when i write an address on the field, autocomplete don't work.

Im using last realia 4.1.2

thanks in advance

**Comment by eriktelepovsky** [comment]
For the lookup / autocomplete to work, you need to enable "Google Places API Web Service" API for your project in Google Cloud Platform Console.

More info: http://stackoverflow.com/a/38297390
