### ISSUE TITLE
Create custom resigtration form 

### ISSUE THREAD

**Issue by RezaRamezanpour** [PragmaticMates/realia#4]
First of all, many thanks for the great, awesome plugin .
As i mentioned in title,  My question is how i can create custom registration with full agents information to use it later? i don’t want to users see default WordPress reg page.
Thanks!

**Comment by eriktelepovsky** [comment]
Hi. Thank you for your kind words.

There are 2 shortcodes available: ``[realia_register]`` and ``[realia_change_agent_profile]``
