### ISSUE TITLE
Adding properties attribute to widget

### ISSUE THREAD

**Issue by RezaRamezanpour** [PragmaticMates/realia#5]
Hi, How i can adding property attributes (for example number of beds,bath, etc) in the properties listing? (for demonstration see [Megareal theme](http://preview.themeforest.net/item/megareal-real-estate-portal-wordpress-theme/full_screen_preview/11965035) ) 
![ex](https://user-images.githubusercontent.com/12220097/32062183-48570bee-ba63-11e7-917f-932420a6b6d8.png)

**Comment by eriktelepovsky** [comment]
You can override template file in your child theme and change it according to your needs.

**Comment by RezaRamezanpour** [comment]
Thank you, but how i can get that attributes from the right way?

**Comment by eriktelepovsky** [comment]
All attributes are saved as post meta information you can read using function from WordPress API:

https://developer.wordpress.org/reference/functions/get_post_meta/

**Comment by RezaRamezanpour** [comment]
OK, I've checked the plugin, it just has two method for getting price & type. So I’ve decided to use `get_post_meta`. As you advise too.
