### ISSUE TITLE
Realia setup custom payment gateway

### ISSUE THREAD

**Issue by RezaRamezanpour** [PragmaticMates/realia#6]
hi,
I've readed the Realia docs and found `realia_payment_gateways` but i don’t know how to use it, and how it works. Please give me a code example for setting up gateways(for example paypal  or whatever).
Thank you.

**Comment by eriktelepovsky** [comment]
Feel free to check the implementation of realia-paypal plugin for more details.

**Comment by RezaRamezanpour** [comment]
Where i can find that plugin? it does not exists in wp plugins repo.

**Comment by eriktelepovsky** [comment]
That plugin is available in any of our WordPress themes based on Realia on ThemeForest:

https://themeforest.net/user/aviators

**Comment by RezaRamezanpour** [comment]
Thanks erik. I’ve wrote my own payment plugin for realia (not paypal). i'm going to submit it to the WordPress repository.
